using services head patch put delete
afranco7/psl-workshop-api-testing-js pull request #2
Opened 2017-09-25 22:48 UTC by afranco7

2017-09-25 22:54 UTC, germandavid85 requested changes

2017-09-25 22:54 UTC, germandavid85 commented on test/MyFirstApiConsume.test.js
> +    return agent.get('https://httpbin.org/ip').then((response) => {
organiza la indentación para que sea de 2 espacios

2017-09-25 22:54 UTC, germandavid85 commented on test/MyFirstApiConsume.test.js
> +  });
adicionar linea en blanco al final del archivo

2017-09-25 23:09 UTC, afranco7 commented on test/MyFirstApiConsume.test.js
> +    return agent.get('https://httpbin.org/ip').then((response) => {
doble espacio entre cada test?

2017-09-25 23:48 UTC, germandavid85 commented on test/MyFirstApiConsume.test.js
> +    return agent.get('https://httpbin.org/ip').then((response) => {
dos espacios en la sangría
asi:
```js
it('Consume GET Service', () => {
  return agent.get('https://httpbin.org/ip').then((response) => {
```

en vez de:
```js
it('Consume GET Service', () => {
    return agent.get('https://httpbin.org/ip').then((response) => {
```

2017-09-26 18:28 UTC, germandavid85 approved these changes

2017-09-26 18:35 UTC, merged