Test reports
afranco7/psl-workshop-api-testing-js pull request #6
Opened 2017-09-29 22:16 UTC by afranco7

2017-09-29 22:54 UTC, aperdomob requested changes
Falta la configuración del travis

2017-09-29 22:54 UTC, aperdomob commented on test/GithubApi.Authentication.test.js
> +
eliminar espacios

2017-10-02 16:08 UTC, aperdomob commented on test/GithubApi.Authentication.test.js
> +
Aun falta esta correción

2017-10-02 16:19 UTC, aperdomob commented on test/GithubApi.Authentication.test.js
> +     }));
La idea es que no te aparezca el fin de linea, ya lo corrijo yo

![image](https://user-images.githubusercontent.com/17033942/31087666-81626cde-a763-11e7-87b0-abac7d7e97e6.png)

2017-10-02 16:19 UTC, afranco7 commented on test/GithubApi.Authentication.test.js
> +     }));
gracias

2017-10-02 16:22 UTC, aperdomob requested changes

2017-10-02 16:22 UTC, aperdomob commented on package.json
>      "test": "mocha -t 5000 --reporter mochawesome --reporter-options reportDir=report,reportFilename=ApiTesting"
aqui deberías tener 
```
"test": "npm run lint && mocha -t 5000 --reporter mochawesome --reporter-options reportDir=report,reportFilename=ApiTesting"
```

2017-10-02 16:49 UTC, aperdomob requested changes

2017-10-02 16:49 UTC, aperdomob commented on test/GithubApi.Authentication.test.js
> +it('Via OAuth2 Tokens by parameter', () =>
agrega este it dentro del describe (Todos it debería estar dentro de un describe)

2017-10-02 16:57 UTC, aperdomob approved these changes

2017-10-02 17:22 UTC, merged